spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community_batch?characterEncoding=UTF-8&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # 테스트용 테이블 생성 설정
